#!/usr/bin/env python
# -*- coding: utf-8 -*-

import optparse
from os import path, rename
from string import ascii_letters
from random import randint, choice
from pdb import set_trace


def main():
    opt = optparse.OptionParser(description='Rename files random names',
                                    prog='rand_name',
                                    version='0.1',
                                    usage='rand_name Файлы')
    options, arguments = opt.parse_args()

    if not arguments:
        print(u'Нечего переименовывать!')
        return

    for filename in arguments:
        if path.exists(filename):
            full_name = path.basename(filename).split('.')
            if len(full_name) > 1:
                new_name = ''.join([choice(ascii_letters)\
                    for x in range(1, randint(5, 10))]) + '.' + full_name[-1]
                rename(filename,
                    path.join(path.dirname(filename), new_name))


if __name__ == '__main__':
    main()